### PR TITLE
feat: rename remove-git-branch.sh to remove-git-branch and update documentation

### PR DESCRIPTION
**Pull request by dym-ok**
I suggest renaming the script to drop `*.sh` file extension and recommend using the script directly without an alias.
What do you think about it?

### CODE REVIEW

**Comment by dym-ok** [comment]
Also, `README.md` [mentions](https://github.com/pavlovic265/remove-git-branch/blob/main/README.md#remove-git-branches-locally) option -d and I don't see it anywhere in code or documentation, what do I miss?

**Comment by pavlovic265** [comment]
> I suggest renaming the script to drop `*.sh` file extension and recommend using the script directly without an alias.
> What do you think about it?

This is great 💪 . Like this approach more.

**Comment by pavlovic265** [comment]
> Also, `README.md` [mentions](https://github.com/pavlovic265/remove-git-branch/blob/main/README.md#remove-git-branches-locally) option -d and I don't see it anywhere in code or documentation, what do I miss?

I see why this is confusing.  `-d` is used by default when you want to delete git branches, you can see it [here](https://github.com/pavlovic265/remove-git-branch/blob/71956ffca40eda29b5e2a8498ff742863e25b201/remove-git-branch.sh#L91), so if you have some branches that have unmerged changes they will not be deleted. In that case, there is `-f` flag which will force delete them.

Now when I read it again, it should be removed or reworded.

**Review by pavlovic265 — COMMENTED** [review]
Thanks for contributing!  🚀

**Review by pavlovic265 — APPROVED** [review]

**Comment by dym-ok** [comment]
I updated the top section in `README.md` to make it clear that we're talking about `git branch -d`

**Pull request merged**
